#!/bin/bash
if [ "$#" -lt 1 ]; then
	echo "Illegal number of parameters"
elif [ $1 = "import" ]; then
	sudo cat ~/.zshrc > ~/.zshrc_copy
	sudo cat ~/Dropbox/Ustawienia\ aplikacji/zshrc/zshrc.txt > ~/.zshrc	
	echo "imported"
elif [ $1 = "export" ]; then
	sudo cat ~/.zshrc > ~/Dropbox/Ustawienia\ aplikacji/zshrc/zshrc.txt

	start_dir=$(pwd)
	cd ~/repositories/terminal_config

	sudo cat ~/.zshrc > ohmyzsh/zshrc.txt
	git add ohmyzsh/zshrc.txt
	git commit -m "zsh config $(date +%Y-%m-%d)" ohmyzsh/zshrc.txt
	git stash
	git pull origin master
	git push origin master
	git stash pop

	cd $start_dir

	echo "exported"
else
	echo "invalid parameter"
fi